description: A new Flutter project.
name: crackd_timer

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0-165.1.beta <3.0.0"

dependencies:
  animations: ^2.0.3
  audioplayers: ^4.0.1
  auto_route: ^7.2.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.1.0
  google_fonts: ^3.0.1
  intl: ^0.18.1
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  mockito: ^5.4.1
  path: ^1.8.2
  path_provider: ^2.0.11
  provider: ^6.0.3
  riverpod: ^2.3.6
  sembast: ^3.3.0
  uuid: ^3.0.6

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.1.2
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/emojis/
    - assets/sounds/

  fonts:
    - family: FuturaPT
      fonts:
        - asset: assets/fonts/FuturaPT-Std-Book.otf
        - asset: assets/fonts/FuturaPT-Std-Bold.otf
          weight: 600
