import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

final List<IconData> iconLists = [
  FontAwesomeIcons.truckField,
  FontAwesomeIcons.beerMugEmpty,
  FontAwesomeIcons.bomb,
  FontAwesomeIcons.bookJournalWhills,
  FontAwesomeIcons.bookSkull,
  FontAwesomeIcons.broomBall,
  FontAwesomeIcons.brush,
  FontAwesomeIcons.businessTime,
  FontAwesomeIcons.cameraRetro,
  FontAwesomeIcons.code,
  FontAwesomeIcons.dragon,
  FontAwesomeIcons.dumpsterFire,
  FontAwesomeIcons.fire,
  FontAwesomeIcons.floppyDisk,
  FontAwesomeIcons.fontAwesome,
  FontAwesomeIcons.ghost,
  FontAwesomeIcons.golfBallTee,
  FontAwesomeIcons.guitar,
  FontAwesomeIcons.handSparkles,
  FontAwesomeIcons.handSpock,
  FontAwesomeIcons.hatWizard,
  FontAwesomeIcons.iceCream,
  FontAwesomeIcons.jedi,
  FontAwesomeIcons.meteor,
  FontAwesomeIcons.motorcycle,
  FontAwesomeIcons.mugSaucer,
  FontAwesomeIcons.personBooth,
  FontAwesomeIcons.poo,
  FontAwesomeIcons.recordVinyl,
  FontAwesomeIcons.skullCrossbones,
  FontAwesomeIcons.socks,
  FontAwesomeIcons.stroopwafel,
  FontAwesomeIcons.umbrellaBeach,
  FontAwesomeIcons.userAstronaut,
  FontAwesomeIcons.userSecret,
  FontAwesomeIcons.virus,
  FontAwesomeIcons.whiskeyGlass,
  FontAwesomeIcons.bilibili,
];
